g

diff --git a/.github/workflows/pr_scan.yml b/.github/workflows/pr_scan.yml
--- a/.github/workflows/pr_scan.yml
+++ b/.github/workflows/pr_scan.yml
@@ -18,7 +18,7 @@ jobs:
         run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
       - name: Run Snyk scan
-        run: snyk test --all-projects --json --all-issues > snyk_report.json
+        run: snyk test --all-projects --json --all-issues --project-id=491d9894-c158-4a71-8a53-7b1101c1f535 > snyk_report.json  || echo "::set-env name=SCAN_FAILED::true"
 
       - name: Check Snyk scan results
         run: |
